# Generated by Django 4.2.28 on 2026-03-12 22:00

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Funcionario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("data_nascimento", models.DateField()),
                (
                    "sexo",
                    models.CharField(
                        choices=[("M", "Masculino"), ("F", "Feminino")], max_length=1
                    ),
                ),
                ("cpf", models.CharField(max_length=11, unique=True)),
                ("salario", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "cargo",
                    models.IntegerField(
                        choices=[
                            (1, "Administrador"),
                            (2, "Gerente"),
                            (3, "Colaborador"),
                        ]
                    ),
                ),
                ("data_contratacao", models.DateField(auto_now_add=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("modificado_em", models.DateTimeField(auto_now=True)),
                ("telefone", models.CharField(max_length=20)),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[("CPF", "CPF"), ("CNPJ", "CNPJ")],
                        max_length=4,
                        unique=True,
                    ),
                ),
                (
                    "tipo_pessoa",
                    models.CharField(
                        choices=[("Física", "Física"), ("Jurídica", "Jurídica")],
                        max_length=8,
                    ),
                ),
                ("numero_documento", models.CharField(max_length=14, unique=True)),
                ("email", models.EmailField(max_length=254)),
                ("telefone", models.CharField(max_length=20)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("modificado_em", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Endereco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("logradouro", models.CharField(max_length=100)),
                ("numero", models.IntegerField()),
                ("bairro", models.CharField(max_length=100)),
                ("cidade", models.CharField(max_length=100)),
                (
                    "uf",
                    models.CharField(
                        choices=[
                            ("AC", "Acre"),
                            ("AL", "Alagoas"),
                            ("AP", "Amapá"),
                            ("BA", "Bahia"),
                            ("CE", "Ceará"),
                            ("DF", "Distrito Federal"),
                            ("ES", "Espírito Santo"),
                            ("GO", "Goiás"),
                            ("MA", "Maranhão"),
                            ("MG", "Minas Gerais"),
                            ("MS", "Mato Grosso do Sul"),
                            ("MT", "Mato Grosso"),
                            ("PA", "Pará"),
                            ("PB", "Paraíba"),
                            ("PE", "Pernambuco"),
                            ("PI", "Piauí"),
                            ("PR", "Paraná"),
                            ("RJ", "Rio de Janeiro"),
                            ("RN", "Rio Grande do Norte"),
                            ("RO", "Rondônia"),
                            ("RR", "Roraima"),
                            ("RS", "Rio Grande do Sul"),
                            ("SC", "Santa Catarina"),
                            ("SE", "Sergipe"),
                            ("SP", "São Paulo"),
                            ("TO", "Tocantins"),
                        ],
                        max_length=2,
                    ),
                ),
                ("cep", models.CharField(max_length=9)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("modidicado_em", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Habilidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
                ("descricao", models.TextField(blank=True, null=True)),
                ("ativa", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("modificado_em", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Não iniciado"),
                            (1, "Em andamento"),
                            (2, "Concluído"),
                            (3, "Bloqueado"),
                            (4, "Cancelado"),
                        ],
                        default=0,
                    ),
                ),
                ("descricao", models.TextField()),
                ("custo", models.DecimalField(decimal_places=2, max_digits=10)),
                ("data_entrega_prevista", models.DateField(blank=True, null=True)),
                ("data_entrega_real", models.DateField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("modidicado_em", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projetos",
                        to="app.cliente",
                    ),
                ),
                (
                    "gerente",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projetos_gerenciados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tarefa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                ("ativa", models.BooleanField(default=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Não iniciado"),
                            (1, "Em andamento"),
                            (2, "Concluído"),
                            (3, "Bloqueado"),
                            (4, "Cancelado"),
                        ],
                        default=0,
                    ),
                ),
                ("data_entrega_prevista", models.DateField(blank=True, null=True)),
                ("data_entrega_real", models.DateField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("modidicado_em", models.DateTimeField(auto_now=True)),
                (
                    "colaborador",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tarefas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "habilidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tarefas",
                        to="app.habilidade",
                    ),
                ),
                (
                    "projeto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tarefas",
                        to="app.projeto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FuncionarioHabilidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "colaborador",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "habilidade",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.habilidade",
                    ),
                ),
            ],
            options={
                "unique_together": {("colaborador", "habilidade")},
            },
        ),
        migrations.AddField(
            model_name="cliente",
            name="endereco",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cliente",
                to="app.endereco",
            ),
        ),
        migrations.AddField(
            model_name="funcionario",
            name="endereco",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="funcionario",
                to="app.endereco",
            ),
        ),
        migrations.AddField(
            model_name="funcionario",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AddField(
            model_name="funcionario",
            name="habilidades",
            field=models.ManyToManyField(
                related_name="funcionarios",
                through="app.FuncionarioHabilidade",
                to="app.habilidade",
            ),
        ),
        migrations.AddField(
            model_name="funcionario",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
    ]
