# Generated by Django 4.2.28 on 2026-03-01 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="funcionario",
            name="tipo_funcionario",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.tipofuncionario",
            ),
        ),
        migrations.AlterField(
            model_name="habilidade",
            name="descricao",
            field=models.TextField(blank=True, null=True),
        ),
    ]
