# Generated by Django 4.2.28 on 2026-03-14 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projeto",
            name="is_ativo",
            field=models.BooleanField(default=True),
        ),
    ]
