# Generated by Django 4.2.28 on 2026-03-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_funcionario_habilidades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='habilidades',
            field=models.ManyToManyField(blank=True, null=True, related_name='funcionarios', through='app.FuncionarioHabilidade', to='app.habilidade'),
        ),
    ]
