# Generated by Django 4.2.28 on 2026-03-14 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_projeto_is_ativo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="projeto",
            old_name="modidicado_em",
            new_name="modificado_em",
        ),
    ]
