# Generated by Django 4.2.28 on 2026-03-01 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_funcionario_tipo_funcionario_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="tipo_cliente",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.tipocliente",
            ),
        ),
        migrations.AlterField(
            model_name="tipofuncionario",
            name="descricao",
            field=models.TextField(blank=True, null=True),
        ),
    ]
