# Generated by Django 4.2.28 on 2026-03-14 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_rename_modidicado_em_projeto_modificado_em"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tarefa",
            old_name="modidicado_em",
            new_name="modificado_em",
        ),
    ]
