# Generated by Django 4.2.28 on 2026-03-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_cliente_tipo_cliente_alter_tipofuncionario_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='senha',
            field=models.CharField(default='123', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tipocliente',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tipofuncionario',
            name='funcao',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Gerente', 'Gerente'), ('Colaborador', 'Colaborador')], max_length=13, unique=True),
        ),
    ]
