# Generated by Django 4.2.28 on 2026-03-05 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_funcionario_senha_alter_tipocliente_descricao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='modidicado_em',
            new_name='modificado_em',
        ),
    ]
