# Generated by Django 4.2.28 on 2026-03-07 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_rename_modidicado_em_funcionario_modificado_em"),
    ]

    operations = [
        migrations.RenameField(
            model_name="habilidade",
            old_name="modidicado_em",
            new_name="modificado_em",
        ),
    ]
