# Generated by Django 4.2.28 on 2026-03-07 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_rename_modidicado_em_habilidade_modificado_em"),
    ]

    operations = [
        migrations.AlterField(
            model_name="funcionario",
            name="contato",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="funcionario",
                to="app.contato",
            ),
        ),
    ]
